devrsi0n/chirpy

README.md, src/blocks/Analytics/stats/conversions/index.tsx, src/blocks/Analytics/stats/conversions/prop-breakdown.tsx, src/blocks/Analytics/stats/current-visitors.tsx, src/blocks/Analytics/stats/locations/countries-map.tsx, src/blocks/Analytics/stats/modals/entry-pages.tsx, src/blocks/Analytics/stats/modals/exit-pages.tsx, src/blocks/Analytics/stats/modals/google-keywords.tsx, src/blocks/Analytics/stats/modals/pages.tsx, src/blocks/Analytics/stats/modals/referrer-drilldown.tsx, src/blocks/Analytics/stats/modals/sources.tsx, src/blocks/Analytics/stats/pages/page-rank.tsx, src/blocks/Analytics/stats/sources/referrer-list.tsx, src/blocks/Analytics/stats/sources/search-terms.tsx, src/blocks/Analytics/stats/sources/source-list.tsx, src/blocks/Analytics/stats/visitor-graph.tsx, src/blocks/Analytics/url.ts, src/pages/analytics/[domain].tsx, src/pages/auth/sign-in.tsx, src/types/page.type.ts
=> docs: update document

src/contexts/ThemeProvider/WidgetThemeProvider.tsx, src/pages/theme/[domain].tsx
=> fix: widget theme affects site styles on theme editor

README.md, src/blocks/Features/Features.tsx
=> docs: tweak feature text and github readme

posts/blog/open-source.mdx, posts/privacy-policy.mdx, src/blocks/Features/Features.tsx
=> docs: polish feature text and blog

src/contexts/ThemeProvider/SiteThemeProvider.tsx, src/contexts/ThemeProvider/WidgetThemeProvider.tsx, src/styles/global-styles.ts
Remove the preset background of widget. We'll make a background theme configuration to support customization.
=> fix: remove widget background

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .prettierignore, cypress/support/commands.ts, cypress/support/index.ts
=> Fix: do not send request to server with cypress intercept

cypress/support/commands.ts, src/blocks/Analytics/stats/pages/page-rank.tsx, src/blocks/Analytics/stats/sources/referrer-list.tsx, src/blocks/Analytics/stats/sources/source-list.tsx
Also intercept the signout request to avoid reaching the server to reduce the falsy error alerts.
Al
=> fix: missing source data and truncate link

README.md, posts/blog/open-source.mdx, src/blocks/Features/Features.tsx, src/blocks/IntegrateGuide/IntegrateGuide.tsx, src/styles/global-styles.ts
=> fix: focus style on safaric and polish docs

README.md, posts/blog/open-source.mdx, src/blocks/Features/Features.tsx, src/pages/widget/comment/[pageURL].tsx, src/pages/widget/comment/details/[commentId].tsx
=> docs: fix broken url and increase isr time

CONTRIBUTING.md, package.json
1. Update the doc for setting up the frontend only.
2. Fix ling rules for different file types.
To make and test UI changes, we can skip all the back-end setup.
=> Update front-end setup and lint rules

cypress/integration/home/header.spec.ts, src/blocks/comment-card/comment-card.tsx, src/blocks/rich-text-editor/stories/rich-text-editor.stories.tsx, src/blocks/user-menu/user-menu.tsx, src/components/box/box.tsx, src/components/box/index.ts, src/components/card/card.tsx, src/components/menu/menu.tsx, src/components/text/text.tsx
=> fix: menu item clickable area

package-lock.json, package.json
=> fix: renovate priority

src/__tests__/mocks/mock-use-session.ts, src/pages/api/auth/[...nextauth].ts, src/pages/auth/redirecting.tsx, types/next-auth.d.ts
=> refactor: use next-auth callback url 

src/components/badge/badge.tsx, src/components/button/button.tsx, src/components/logo/logo.tsx
=> feat: add environment badges

src/external/sw/index.ts
=> fix: service worker isn't working

emails/package-lock.json, emails/src/layouts/main.html, src/blocks/notification-hub/notification-item.tsx, src/server/services/email/templates/notification.html, src/server/services/email/templates/verification-request.html, src/server/services/email/templates/welcome.html
=> feat: add unsubscribe button to emails

src/contexts/notification-context/notification-provider.tsx, src/contexts/notification-context/use-reload-when-sw-change.ts, src/contexts/notification-context/utilities.ts
=> fix: page can't be opened on safari

cypress/integration/home/footer.spec.ts, cypress/integration/home/header.spec.ts, package-lock.json, package.json, src/blocks/analytics/analytics.tsx, src/blocks/comment-card/comment-card.tsx, src/blocks/comment-trees/comment-trees.tsx, src/blocks/integrateGuide/integrate-guide.tsx, src/blocks/layout/layout.module.scss, src/blocks/page-title/page-title.tsx, src/blocks/project-card/page-view-stats.tsx, src/blocks/project-card/project-card.tsx, src/blocks/side-bar/side-bar.tsx, src/blocks/side-menu/side-menu.tsx, src/blocks/sign-in-button/sign-in-button.tsx, src/components/dialog/dialog.tsx, src/components/menu/menu.tsx, src/components/toast/toast-item.tsx, src/pages/404.tsx, src/pages/auth/welcome.tsx, src/pages/dashboard/index.tsx, src/pages/theme/[domain].tsx, src/server/services/email/send.ts, src/styles/common.ts
=> fix: styles while migrating to tailwindcsss 3

turbo.json
=> fix(turbo): add outputs

apps/main/src/blocks/notification-hub/notification-item.tsx, apps/main/src/hooks/use-is-widget.ts
=> fix(notification-hub): should open notification link in new tab

package.json, pnpm-lock.yaml
=> fix: pnpm install error

apps/main/package.json, apps/main/src/__tests__/jest.setup.ts, apps/main/src/blocks/layout/widget-layout.tsx, apps/main/src/blocks/user-menu/user-menu.tsx, apps/main/src/components/link/link.tsx, apps/main/src/hooks/use-sign-in-window.ts, apps/main/src/hooks/use-widget-side-effects.ts, apps/main/src/lib/configurations.ts, apps/main/src/lib/constants.ts, apps/main/src/lib/gql-client.ts, apps/main/src/pages/widget/comment/[pageURL].tsx, apps/main/src/pages/widget/comment/details/[commentId].tsx, pnpm-lock.yaml
=> feat: grapgql cache in indexedDB and fix signout doesn't work on widget pages

apps/e2e/package.json, apps/emails/package.json, apps/main/src/blocks/analytics/stats/modals/sources.tsx, apps/main/src/pages/_app.tsx, apps/main/src/server/services/notification/push-web-notification.ts, apps/main/src/server/services/page.ts, apps/service-worker/package.json, packages/prettier-config-chirpy/package.json
=> feat: integrate with axiom

.changeset/friendly-news-think.md, apps/main/src/blocks/notification-hub/notification-hub.tsx, apps/main/src/pages/analytics/[domain].tsx
=> fix(analytics): max width

apps/main/package.json, apps/main/src/components/button/base-button.tsx, pnpm-lock.yaml
Also removed a lot of bundle size
=> fix: remove unexpected clicking outlines

apps/comment-bootstrapper/src/lib/comment-bootstrapper.ts, apps/comment-bootstrapper/src/lib/theme-observer.ts, apps/main/src/__tests__/fixtures/server/graphql-handlers.ts, apps/main/src/__tests__/fixtures/server/rest-handlers.ts, apps/main/src/blocks/notification-hub/__tests__/notification-hub.test.tsx, apps/main/src/blocks/rich-text-editor/format-buttons.tsx, apps/main/src/components/select/select.tsx, apps/main/src/hooks/use-widget-side-effects.ts, apps/main/src/lib/constants.ts, apps/main/src/pages/_app.tsx, apps/main/src/pages/play.tsx
Use separate theme config for widgets
Closes #122
=> feat: control widget theme

apps/e2e/cypress/e2e/home/header.spec.ts, apps/main/src/blocks/comment-widget-preview/comment-widget-preview.tsx, apps/main/src/blocks/comment-widget-preview/home-comment-widget-preview.tsx, apps/main/src/blocks/comment-widget-preview/preview-data.ts, apps/main/src/blocks/theme-editor/__tests__/theme-editor.test.tsx, apps/main/src/blocks/theme-editor/theme-editor.tsx, apps/main/src/pages/index.tsx, apps/main/src/pages/theme/[domain].tsx
=> fix(home-page): ssr hydration mismatch

.changeset/config.json, apps/main/package.json, apps/main/posts/docs/features/analytics.mdx, apps/main/posts/docs/features/dark-mode.mdx, apps/main/posts/docs/features/moderate.mdx, apps/main/posts/docs/features/theme.mdx, apps/main/posts/docs/get-started.mdx, apps/main/src/blocks/comment-card/comment-card.tsx, apps/main/src/blocks/layout/layout.module.scss, apps/main/src/blocks/rich-text-editor/rte-popover-button.tsx, apps/main/src/components/select/select.module.scss, packages/eslint-config-chirpy/package.json, pnpm-lock.yaml
fix(rte): black background on dark mode
fix(storybook): build error
=> Fix rte styles and storybook build error

apps/emails/src/layouts/main.html, apps/main/src/server/services/email/templates/notification.html, apps/main/src/server/services/email/templates/verification-request.html, apps/main/src/server/services/email/templates/welcome.html
=> fix: email unsubscript not working

README.md, apps/main/src/blocks/theme-editor/theme-editor.tsx, apps/main/src/blocks/theme-editor/utilities.ts, apps/main/src/middleware.ts, apps/main/src/pages/api/auth/delete/facebook.ts, apps/main/src/pages/api/content-classifier/toxic-text.ts, apps/main/src/pages/api/mutation-event/index.ts, apps/main/src/pages/api/page.ts, apps/main/src/pages/api/revalidate/widgets.ts, apps/main/src/pages/play.tsx, apps/main/src/server/common/api-error.ts, apps/main/src/server/common/api-handler.ts, apps/main/src/server/graphql/generated/project.tsx, apps/main/src/server/graphql/project.graphql, apps/main/src/server/services/revalidate/widgets.ts, apps/main/src/server/utilities/revalidate.ts
- fix: revalidate widgets after theme changing
- Add twitter badge to the readme
=> fix: revalidate widgets after theme changing

.gitignore, .npmrc, README.md, apps/main/package.json, apps/main/src/__tests__/fixtures/server/graphql-handlers.ts, apps/main/src/__tests__/jest.setup.ts, apps/main/src/__tests__/mocks/mock-framer-motion.tsx, apps/main/src/blocks/powered-by/__tests__/powered-by.test.tsx, apps/main/src/blocks/theme-editor/theme-editor.tsx, apps/main/src/blocks/theme-editor/utilities.ts, apps/main/src/components/alert/__tests__/alert.test.tsx, apps/main/src/components/alert/alert.tsx, apps/main/src/components/text-field/__tests__/text-field.test.tsx, apps/main/src/pages/api/revalidate/theme.ts, apps/main/src/pages/theme/[domain].tsx, apps/main/src/server/graphql/generated/project.tsx, apps/main/src/server/graphql/project.graphql, apps/main/src/server/services/revalidate/theme.ts, pnpm-lock.yaml
=> fix(theme): stale theme page after refreshing

apps/main/src/server/services/auth/auth-adapter.ts, apps/main/src/server/utilities/object.ts
=> fix: can't sign-in with email

.github/workflows/cypress.yml, apps/e2e/cypress.config.ts, apps/e2e/cypress/e2e/dashboard/project.spec.ts, packages/ui/src/pages/dashboard/index.tsx
=> fix(dashboard): missing the project after creating and show error with duplicated domain

apps/comment-bootstrapper/src/index.ts
=> fix(widget): comment widget disappeared after clicking back button

.husky/pre-commit, apps/main/src/pages/index.tsx, packages/ui/src/blocks/faqs/faq-data.tsx, packages/ui/src/blocks/faqs/faqs.tsx, packages/ui/src/blocks/features/features.tsx, packages/ui/src/pages/home.tsx
=> Improved landing page's copies

packages/trpc/src/router/site/validations.ts, packages/ui/src/hooks/use-form/type.ts, packages/ui/src/hooks/use-form/use-form.ts, packages/ui/src/pages/app/site/create/site-form.tsx
=> fix: use-form-typing
